[book]
title = "Rust By Example 日本語版"
description = "A description"
author = "The Rust Community"
language = "ja"

[build]
build-dir = "docs"

[output.html]
additional-css = ["css/custom.css"]
git-repository-url = "https://github.com/rust-lang-ja/rust-by-example-ja"

[output.html.playpen]
editable = true
editor = "ace"

[output.html.fold]
enable = true
